name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }} 
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        time=$(date "+%Y%m%d")
        docker build . --file Dockerfile --tag ${{ secrets.HOST }}/zerotier-controller:$time && docker push ${{ secrets.HOST }}/zerotier-controller:$time
