name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_URL }}/zerotier-controller:v1.8.9
      
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.6
      with:
        image: zerotier-controller
        tags: ${{ secrets.REGISTRY_URL }}/zerotier-controller:v1.8.9
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }} 
