name: Docker Image CI

on:
  push
  
jobs:

  build:

    runs-on: ubuntu-20.04
    
    steps:
    - name: Test secrets
      run: echo "my registry is ${{ secrets.HOST }}"
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.HOST }}/zerotier-controller:v1.8.9
      
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.6
      with:
        image: zerotier-controller
        tags: ${{ secrets.HOST }}/zerotier-controller:v1.8.9
        registry: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }} 
